### PR TITLE
19262: Migrates away from seaborn

### PR DESCRIPTION
**Pull request by jdbeel**

### CODE REVIEW

**Comment by cademack** [comment]
Some of these plots are not rendering nicely (see 5-bias-mitigation)

**Review by mkoistinen — DISMISSED** [review]
⭐

**Review by jackx111 — COMMENTED** [review]
Version warning in this, "Version 16.0.0 ... using 15.0.11"

**Review by jackx111 — APPROVED** [review]

**Review by jackx111 — CHANGES_REQUESTED** [review]
drift monitoring graph

**Review by mkoistinen — DISMISSED** [review]

**Pull request merged**
